# Generated by Django 4.1.1 on 2023-01-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topic_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='private',
        ),
    ]
